name: DEPLOY-LINUX-STAGING

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Linux:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/master'
    needs: [build-linux]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'https://github.com/casa-vega/HelloWorldCmakeSample'
    steps:
      - name: Deploy
        run: echo I am deploying! 
