name: DEPLOY-LINUX-STAGING

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  Linux:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [CI-LINUX]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'https://github.com/casa-vega/HelloWorldCmakeSample'
    steps:
      - name: Deploy
        run: echo I am deploying! 
