name: LINUX CI+CD

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Running cmake (linux)
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake .. && make
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-hello-world
        path: build/CMakeHelloWorld
        retention-days: 2

  deploy-linux-staging:
    name: Deploy Linux to Staging 
    if: github.event.ref == 'refs/heads/master'
    needs: [build-linux]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://stage.cadence.com'
    steps:
      - name: Deploy
        run: echo I am deploying!  

  deploy-linux-production:
    name: Deploy Linux to Production 
    needs: [deploy-linux-staging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://prod.cadence.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
